version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 

  app:
    depends_on:
      - db
    build: .
    ports:
      - "5050:5050"
    restart: always
    environment:
      FLASK_ENV: ${FLASK_ENV}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI} 

volumes:
  db_data: {}
